### ISSUE TITLE
Age UK directory

### ISSUE THREAD

**Issue by GreenCChampion** [folklabs/connecting-communities#12]
Care organisations in Lambeth are using this Age UK directory as a benchmark for some asset mapping. It has been referenced by Southwark & Lambeth Integrated Care (SLIC) and SW Locality Local Care Network.

http://www.ageuk.org.uk/lambeth/our-services/directory/

I would be interested to know if this can be part of the Ohana pilot. they have 2 people full time working on developing this database and it's something like 70% accurate according to a manager I met.
I am setting up a meeting for myself and Giles with Age UK Lambeth

**Comment by pmackay** [comment]
@GreenCChampion have you fixed a date yet, or had a meeting? Would be great to know more about how Age UK store their organisation data and publish it.

**Comment by GreenCChampion** [comment]
We have a meeting with them this week - Thursday morning 9.30. Giles is going - I am not yet sure if I can make it.

**Comment by pmackay** [comment]
Closing as meeting is past. Unclear after talking with Giles how Age UK directory would be part of trial. @GilesGibson shout if you have other thoughts.
