### ISSUE TITLE
Develop custom taxonomy 

### ISSUE THREAD

**Issue by pmackay** [folklabs/connecting-communities#20]
Ohana uses http://openeligibility.org/, but this has a US bias. The HH list is below, which is flat. Do we want to develop a nested list with 2nd level terms?

```
Arts & Crafts
Builders & Tradespeople
Business & Finance
Charities & Appeals
Children & Families
Crime & Policing
Education & Learning
Environment & Parks
Entertainment
Fayres
Food & Drink
Government & Politics
Hair, Beauty & Cosmetics
Health, Sport & Wellbeing
History
Home & Garden Services
Local amenities
Meeting
Music, Film, Dance
Pets & Animal care
Religion
Shops & Local economy
Travel & Transport
Volunteering & Community
```

cc @GilesGibson @GreenCChampion @djwesto

**Comment by pmackay** [comment]
Also the terms shown on the homepage are defined manually and are search terms across the site. So any thoughts on specific terms that would be good highlight via the homepage is welcome. 

Is the distinction between regular and emergency items important?

**Comment by djwesto** [comment]
As discussed with Giles today, crucially, we need to point out that there is no categorisation of the GIFTS data set we've imported into the system.

And, there's also no agreed taxonomy for the GIFTS data yet either.

**Comment by GreenCChampion** [comment]
Let's see if there's a taxonomy for the Age UK directory @GilesGibson is meeting with them next Wednesday

**Comment by pmackay** [comment]
On another check, there is a set of categories in the GIFTS data. Have extracted this below. There are 164 categories across ~800 records. There are sub-categories based on separations with the `\` character. 

Do we want to use this directly? 

Advice Services
Advice Services\Advice and Legal Services ( Social Welfare Law)
Advice Services\Advice, Information & Support Service
Advice Services\Direct Payments Support Service
Advice Services\General
Advice Services\Getting out and about
Advice Services\Health & wellbeing
Advice Services\Housing & care homes
Advice Services\Information & Advice - mental health services
Advice Services\Information and Advice (Women Support)
Advice Services\Information, Advice and Advocacy
Advice Services\Legal & money
Advice Services\Living at home
Advice Services\Living with a disability
Advice Services\Looking after someone
Advice Services\Other
Advice Services\Social Welfare Advice Services
Advice Services\Staying safe
Advice Services\Welfare Benefit Advice Services
Arts
Arts\Dance
Arts\Drama
Arts\Film
Arts\Graphic Design
Arts\Music
Arts\Visual Art
BME Support Group
Business
Business\Retail
Capacity Building Services
Children & Young People
Children & Young People\After School
Children & Young People\Early Years
Children & Young People\Education & Training
Children & Young People\Extended Schools
Children & Young People\NEET
Children & Young People\Nursery
Children & Young People\Playschemes  - Summer
Children & Young People\Playschemes - Easter
Children & Young People\Schools
Children & Young People\Schools\Primary
Children & Young People\Schools\Secondary
Children & Young People\Schools\Special
Children & Young People\Youth
Community Assets
Community Centre
Community Development
Community Development\Parks Project
Community Development\Regeneration Project
Community Development\Umbrella Organisation/2nd tier
Community Hubs
Community Organisations
Community Safety
Community Safety\Business Crime Project
Community Safety\Community Safety event
Community Safety\Core Funding Grant
Community Safety\Crime prevention & detection
Community Safety\Drug awareness & Needs Assessment
Community Safety\Football Project
Community Safety\Gang Intervention Programme
Community Safety\Mentoring
Community Safety\Prostitution outreach
Community Safety\Safer Neighbourhood Panel
Community Safety\Targetted interventions
Community Safety\Trauma counselling for victims of crime
Community Safety\Youth Diversion Project
Consultation & Engagement
Crime
Domestic Violence Support
Education & Training
Employment & Training
Environment
Faith Group
Faith Group\Denomination
Faith Group\Denomination\Anglican
Faith Group\Denomination\Anglican & Methodist
Faith Group\Denomination\Baptist
Faith Group\Denomination\Buddhist
Faith Group\Denomination\Christian
Faith Group\Denomination\Evangelical
Faith Group\Denomination\Hindu
Faith Group\Denomination\Incomplete
Faith Group\Denomination\Independent
Faith Group\Denomination\Islam
Faith Group\Denomination\Jewish
Faith Group\Denomination\Methodist
Faith Group\Denomination\Multi Faith
Faith Group\Denomination\Pentecostal
Faith Group\Denomination\Quakers
Faith Group\Denomination\Rastafarian
Faith Group\Denomination\Roman Catholic
Faith Group\Denomination\Seventh Day Adventist
Faith Group\Muslim Community Forum
Faith Group\Other\Charitable organisation
Health & Social Care
Health & Social Care\Adults
Health & Social Care\Advice & Information
Health & Social Care\Children & Families
Health & Social Care\Counselling
Health & Social Care\Day Care Services
Health & Social Care\Disabilities
Health & Social Care\Domiciliary Care
Health & Social Care\GP Surgeries
Health & Social Care\HIV/Aids
Health & Social Care\Learning disabilities
Health & Social Care\Learning disabilities\Adults
Health & Social Care\Mental Health
Health & Social Care\Older people
Health & Social Care\Rehabilitation
Health & Social Care\Resource Centre
Health & Social Care\Respite Care
Health & Social Care\Substance abuse
Health & Social Care\Support Services
Health & Social Care\Transport
Heritage
Housing
Housing\Community Association
Housing\Registered Social Landlord
Housing\Tenants & Residents Assoc
Housing\Tenants & Residents Assoc (Registered)
Infastructure Org/Second Tier
LCF Grant Recipient
Leisure/Play facilities
Lesbian, Gay, Bisexual and Transgender
Lesbian, Gay, Bisexual and Transgender\Gay men
Libraries
Local Services
London CVS (Councils for Voluntary Service)
Manufacturer
Media
Media\Creative & Cultural Industry
Partnerships
Private Sector Organisation
Private Sector Organisation\Advice
Private Sector Organisation\Environment
Private Sector Organisation\Food & Drink
Regeneration
Relief of poverty
Social Enterprise
Social Enterprise\Advice
Social Enterprise\Culture
Social Enterprise\Education & Training
Social Enterprise\Environment
Social Enterprise\Financial
Social Enterprise\Food &Drink
Social Enterprise\Health
Social Enterprise\Housing
Social Enterprise\Retail
Sports
Sports\Club
Sports\Coaching
Sports\Community Event
Statutory Agencies
Statutory Agencies\Local Authority
Statutory Agencies\London Borough of Lambeth
Statutory Agencies\Metropolitan Police
Statutory Agencies\Prison Service (HMP Brixton)
Traffic/Roads
Training
Travel\Rail
VCS - IT Resources & Support\UK Online Centres
Venue for hire
Volunteering
Women's Support Group

**Comment by GreenCChampion** [comment]
This seems like a good starting point

**Comment by GreenCChampion** [comment]
Although looking at it in detail I don't like some of the categories and I can't see parks or libraries for instance. I suspect new categories have been added based on grants given.

**Comment by pmackay** [comment]
What is your preference:
- use it without change
- spend some time updating it but use most of it
- use Herne Hill much simpler list

**Comment by GreenCChampion** [comment]
Is the Herne Hill list the same as the OpenLocal list?

**Comment by pmackay** [comment]
Yes it would be.

For now I'm going to import the taxonomy defined by the GIFTS data, as it
makes it easier to assign for the existing content.

Sounds like we also need to do a review of it later.
