### ISSUE TITLE
Multilingual language support

### ISSUE THREAD

**Issue by pmackay** [folklabs/connecting-communities#21]
The set of languages Ohana shows can easily be customised, and it simply puts the page text through Google Translate. Are there other languages in the Lambeth area that it would be good to support?

@GilesGibson @GreenCChampion

**Comment by GilesGibson** [comment]
Portugese. main language is the Vassall Stockwell area.

**Comment by pmackay** [comment]
Just that? So English and Portugese?

**Comment by GilesGibson** [comment]
for the prototype, yes.
(Sue is adding in a comment here - probably not protocol!) I agree - but would be interested to know if languages below are listed on Ohana - Yoruba, Twi and Somali...

**Comment by GreenCChampion** [comment]
![image](https://cloud.githubusercontent.com/assets/11994995/7701267/6f8037c2-fe1d-11e4-81af-82fc23ef0731.png)
Not sure if you can see this image.
Portuguese is the most widely spoken second language in Lambeth, followed by Yoruba, Twi and Somali, then Polish.

**Comment by GreenCChampion** [comment]
and Spanish...

**Comment by pmackay** [comment]
Portugese and Spanish setup.
