### ISSUE TITLE
'Parks' label on Ohana site

### ISSUE THREAD

**Issue by GreenCChampion** [folklabs/connecting-communities#22]
The parks label on the front page brings up things that are not parks... I clicked on the button on the first page that says Council services/parks and it came up with a list of things that included anything with the name park in it. There are 60-ish parks in Lambeth so I would expect it to come up with those parks. It doesn't look good if the search does not appear relevant.

**Comment by pmackay** [comment]
None of the GIFTS content is categorized yet so those links wont do much.
Also we need to agree on what links would make sense and then probably
manually categorize some content to fit.

**Comment by djwesto** [comment]
We've discussed a solution to this issue today so we're closing this.
