### ISSUE TITLE
Github project labels need to be set up properly

### ISSUE THREAD

**Issue by djwesto** [folklabs/connecting-communities#3]
I think we need the following labels on this project which I will set up. Anyone who disagrees, please leap in and comment:
- as-citizen (for all issues relevant to citizens using the system)
- as-officer (for all issues relevant to council officers using the system)
- as-organiser (for all issues relevant to community organisers using the system)
- as-sysadmin (for all issues relevant to administrators of the backend system)
- bug (bugs, which need to be fixed)
- content/seo (relates to the content of the system)
- documentation (relates to documentation – help or support – for users or developers)
- f-browser (relates to the interface for browsing records)
- f-locations (relates to the location feature)
- f-organisations (relates to the organisation feature)
- f-search (relates to the search feature)
- f-services (relates to the services feature)
- f-upload (relates to the upload feature)
- interface (relates to the visual interface)
- is-duplicate (the problem has already been raised in another issue)
- is-resolved (the problem has been fixed so please close if you agree)
- p1-high (this problem is important)
- p3-low (this problem is minor)
- question (this issue is framed as a question)
- story (this issue is a user story)
- task (this issue is a task)

**Comment by pmackay** [comment]
Yes to these, but leave out `f-crm`. Wanna set those up?

Not sure how often we bother with `is-duplicate`, `is-resolved`.

**Comment by djwesto** [comment]
So you're saying the is-duplicate and is-resolved are simply managed by you closing the issue because it was decided to be a dupe or that it had been resolved?

Fair enough.

**Comment by djwesto** [comment]
Done.

**Comment by GilesGibson** [comment]
@djwesto can we keep the definitions next to the labels in github - easier to remind idiots like me what each label means.

**Comment by pmackay** [comment]
Sadly you cannot add a definition to a label - I asked Github recently if
they could add that :)

**Comment by GilesGibson** [comment]
Can we have a definitions doc somewhere easy to access?

**Comment by djwesto** [comment]
I'll make a wiki. When it's done, I'll post the link to it here. Please save the link as a Chrome bookmarks bar bookmark so you can jump to it whenever you need it: https://github.com/folklabs/connecting-communities/wiki/Issue-Queue-%E2%80%93-Explanation-of-our-labelling-system
